### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by neerajvashistha** [alvinwan/timefhuman#3]
Running this on Python2.7
First error `AttributeError: 'str' object has no attribute 'isnumeric'`, quick fix convert string into unicode.
Second error: `AttributeError: 'list' object has no attribute 'copy'`, quick fix use below for python2.7 
```
    #tokens = tokens.copy()
    tokens = tokens[:]
```
Third error: `AssertionError: Classes must either be a tuple or a type.`, for queries which contain date-time but in string(now unicode) format along with other unessential data, such as, "show me flights to london in next week"

**Comment by sinogermany** [comment]
@neerajvashistha please look at https://github.com/alvinwan/timefhuman/blob/master/.travis.yml#L5
The current tests are only done on version 3.6.2 .

I assume there will be some tweaks to get it working with 2.7 natively. Maybe adopting https://github.com/benjaminp/six would help?
